# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b2ee35f032991abcd81d83b2ba24acbfb3e284eb00a1e63c9450e0b06fe2ccbf27a7095e288dd21ec5665a592fd52111adb5d8fe23bd43ce821a2c7b981401f

test:
  secret_key_base: 0a9d046651c9c2908004e038445f584085d3a63f221e283767b56c9fe80df6abd4c7cf133b7271263777b3574125668d88f91d1a0a2c1c0413efa6af3fffdd42

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
